### ISSUE TITLE
Sign in login logging not automaticly changing to usermainpage

### ISSUE THREAD

**Issue by mertl-tgm** [mertl-tgm/ITP-Projekt#6]

**Comment by mertl-tgm** [comment]
Maybe soolution:
http://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

**Comment by lzuba-tgm** [comment]
Fixed with Commit 3336c4fe4447a4014e87ef3f9197fa0db7c9cf26
