### ISSUE TITLE
Costum image choosing program not working

### ISSUE THREAD

**Issue by mertl-tgm** [mertl-tgm/ITP-Projekt#8]
choose one program, try clicking on another is not working, recognis it always as the first program, which got choosen

**Comment by lzuba-tgm** [comment]
i dont have this issue on webmatrix and apache(xampp)

**Comment by lzuba-tgm** [comment]
also tested on pc and laptop

**Comment by mertl-tgm** [comment]
bug by jquery with microsoft edge

**Comment by mertl-tgm** [comment]
Now working also with Microsoft Edge

Fixed maybe with commit 358b5f461871c9c4a614d9e87175bd04022abc56
